### ISSUE TITLE
Windows & 'curl -s http://192.168.1.70:9999/Assets/runinstrumentation.sh | bash'

### ISSUE THREAD

**Issue by GermMuz** [dtmilano/CulebraTester-public#11]
I am trying to run Culebra with Windows and get a dialog opened up on the web page saying to run: 'curl -s http://192.168.1.70:9999/Assets/runinstrumentation.sh | bash' this is probably very easy in linux land. But how do I do it in Windows???

Thx

**Comment by GermMuz** [comment]
For anyone else out there I solved it by looking at the script that was run. Run the following from a windows cmd shell:

adb shell am instrument -w com.dtmilano.android.culebratester.test/com.dtmilano.android.uiautomatorhelper.UiAutomatorHelperTestRunner

**Comment by dtmilano** [comment]
@GermMuz Thanks for your contribution.  It will help Windows users.
