### ISSUE TITLE
INSTRUMENTATION_RESULT: shortMsg=java.lang.ClassNotFoundException.

### ISSUE THREAD

**Issue by timrijckaert** [dtmilano/CulebraTester-public#2]
# INSTRUMENTATION_RESULT: shortMsg=java.lang.ClassNotFoundException.

Thanks again for the hard work on this repo.
I tried experimenting with your apk's today so I installed both on a Nexus 5 running.
However I can't seem to connect to my PC.
## Repro Steps
1. Connect Android device to PC
2. Open 'Culebra Tester' on Android device.
3. Go to url the service is running on
4. Upon connecting the site prompts 

``` bash
curl -s http://android-5ba28edaf356b383:9999//Assets/runinstrumentation.sh | bash
```
1. Copy and paste code into console.
## Expected
1. Start testing!
## Actual
1. Ubuntu 15.10: 

``` console
tim@tim-Aspire-S7-392:~$ curl -s http://android-5ba28edaf356b383:9999/Assets/runinstrumentation.sh | bash
INSTRUMENTATION_RESULT: shortMsg=java.lang.ClassNotFoundException
INSTRUMENTATION_RESULT: longMsg=java.lang.ClassNotFoundException: Didn't find class "com.dtmilano.android.uiautomatorhelper.UiAutomatorHelperTestRunner" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.dtmilano.android.culebratester.test-1/base.apk", zip file "/data/app/com.dtmilano.android.culebratester-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dtmilano.android.culebratester.test-1/lib/arm, /data/app/com.dtmilano.android.culebratester-1/lib/arm, /vendor/lib, /system/lib]]
INSTRUMENTATION_CODE: 0
tim@tim-Aspire-S7-392:~$ 
```
1.  App quits on device. 
## Debug Info

<table>
<tr><th colspan="2">Platform</th></tr>
<tr><td>Device</td><td>hammerhead</td></tr>
<tr><td>Brand</td><td>google</td></tr>
<tr><td>Board</td><td>hammerhead</td></tr>
<tr><td>Hardware</td><td>LGE</td></tr>
<tr><td>Model</td><td>Nexus 5</td></tr>
<tr><td>API</td><td>23</td></tr>
<tr><td>Build</td><td>hammerhead MOB30M 08a579990245e5c2</td></tr>
<tr><td>Build number</td><td>MOB30M</td></tr>
<tr><th colspan="2">APK</th>
<tr><td>version code</td><td>8010</td>
<tr><td>version name</td><td>0.8.10</td>
<tr><th colspan="2">Display</th></tr>
<tr><td>Size</td><td>1080x1920</td>
</table>

**Comment by dtmilano** [comment]
Version **0.8.12** should fix the issue.
The problem was in the way the APK was minifyed.
