### ISSUE TITLE
Instrumentation error

### ISSUE THREAD

**Issue by IgorGanapolsky** [dtmilano/CulebraTester-public#3]
Hello,
I am running your GUI tool to generate a Python script.  However, upon running this script, I get the following error:

> # 
> ## ERROR: testSomething (**main**.CulebraTests)
> 
> Traceback (most recent call last):
>   File "test.py", line 44, in setUp
>     super(CulebraTests, self).setUp()
>   File "/Library/Python/2.7/site-packages/com/dtmilano/android/viewclient.py", line 4446, in setUp
>     self.vc = ViewClient(self.device, self.serialno, **self.kwargs2)
>   File "/Library/Python/2.7/site-packages/com/dtmilano/android/viewclient.py", line 2535, in **init**
>     self.uiAutomatorHelper = UiAutomatorHelper(device)
>   File "/Library/Python/2.7/site-packages/com/dtmilano/android/uiautomator/uiautomatorhelper.py", line 109, in **init**
>     raise RuntimeError('The target device does not contain the instrumentation for %s' % self.PACKAGE)
> ## RuntimeError: The target device does not contain the instrumentation for com.dtmilano.android.culebratester
> 
> Ran 1 test in 1.830s
> FAILED (errors=1)

Any idea what is causing this?

Thank you,
Igor

**Comment by dtmilano** [comment]
It seems it's failing at

```
        instrumentation = self.adbClient.shell('pm list instrumentation %s' % self.PACKAGE)
        if not re.match('instrumentation:%s/%s \(target=%s\)' % (self.TEST_CLASS, self.TEST_RUNNER, self.PACKAGE), instrumentation):
            raise RuntimeError('The target device does not contain the instrumentation for %s' % self.PACKAGE)
```

which indicates the _instrumentation_ has not been found on the device.
Check the output of `pm list instrumentation`.

**Comment by dtmilano** [comment]
More precisely, command and expected output as follow

```
$ adb shell pm list instrumentation com.dtmilano.android.culebratester
instrumentation:com.dtmilano.android.culebratester.test/com.dtmilano.android.uiautomatorhelper.UiAutomatorHelperTestRunner (target=com.dtmilano.android.culebratester)
```

**Comment by IgorGanapolsky** [comment]
Here:
`instrumentation:com.dtmilano.android.culebratester.test/com.dtmilano.android.uiautomatorhelper.UiAutomatorHelperTestRunner
(target=com.dtmilano.android.culebratester)
instrumentation:com.example.android.apis/.app.LocalSampleInstrumentation
(target=com.example.android.apis)
instrumentation:com.example.android.testing.uiautomator.BasicSample.test/android.support.test.runner.AndroidJUnitRunner
(target=com.example.android.testing.uiautomator.BasicSample)`

**Comment by IgorGanapolsky** [comment]
Here:

```
instrumentation:com.dtmilano.android.culebratester.test/com.dtmilano.android.uiautomatorhelper.UiAutomatorHelperTestRunner (target=com.dtmilano.android.culebratester)
instrumentation:com.example.android.apis/.app.LocalSampleInstrumentation (target=com.example.android.apis)
instrumentation:com.example.android.testing.uiautomator.BasicSample.test/android.support.test.runner.AndroidJUnitRunner (target=com.example.android.testing.uiautomator.BasicSample)
```

**Comment by dtmilano** [comment]
It seems the instrumentation is present.

Does

```
dump --use-uiautomator-helper
```

work?

**Comment by dtmilano** [comment]
**AndroidViewClient/culebra 11.5.13** will give you more explicit messages which I hope help identify the problem.
Please upgrade.

**Comment by IgorGanapolsky** [comment]
Sorry for the late reply.  `dump --use-uiautomator-helper` works.  I just tried to generate the Python script again, and it worked.  However, how do I find out the version of **AndroidViewClient/culebra**?

Thank you,
Igor

**Comment by dtmilano** [comment]
`culebra --version` should print the version.

**Comment by IgorGanapolsky** [comment]
Oh, ok.  I have **11.5.12**.  However, when I try to upgrade AndroidViewClient with `pip`, I get this error:

> androidviewclient==12.0.2 is available (you have 11.5.12)
> Upgrade now? [Y]es, [N]o, [A]ll, [Q]uit y
> Collecting androidviewclient==12.0.2
>   Could not find a version that satisfies the requirement androidviewclient==12.0.2 (from versions: )
> No matching distribution found for androidviewclient==12.0.2

**Comment by dtmilano** [comment]
Just tried `easy_install` on Ubuntu and worked

```
$ sudo easy_install --upgrade androidviewclient
[sudo] password for diego: 
Searching for androidviewclient
Reading https://pypi.python.org/simple/androidviewclient/
Best match: androidviewclient 12.0.2
Downloading https://pypi.python.org/packages/7b/9a/f1f0d06a944cd4922dac097bb3da719e288cc7f58032eb16b7701481fbd1/androidviewclient-12.0.2-py2.7.egg#md5=b7c5a08b172b4998b707dc50f0efd57d
Processing androidviewclient-12.0.2-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/androidviewclient-12.0.2-py2.7.egg
Extracting androidviewclient-12.0.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Removing androidviewclient 11.5.13 from easy-install.pth file
Adding androidviewclient 12.0.2 to easy-install.pth file
Installing culebra script to /usr/local/bin
Installing dump script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/androidviewclient-12.0.2-py2.7.egg
Processing dependencies for androidviewclient
Finished processing dependencies for androidviewclient
```

**Comment by IgorGanapolsky** [comment]
@dtmilano @changetip $1.  Thanks for your efforts.

**Comment by changetip** [comment]
Hi @dtmilano, I've delivered a tip worth 1,528 bits ($1.00) from @IgorGanapolsky.

**[Learn about ChangeTip](https://www.changetip.com/tip-online/github)**
