### ISSUE TITLE
CulebraTester Python Script

### ISSUE THREAD

**Issue by 7ikPDYl3** [dtmilano/CulebraTester-public#5]
Culebra Tester Version 0.8.14
Culebra Tester Instrumentation 0.8.14
Android version 4.4.2
Phone: Motorola Moto G

1) Created a Python27 script on a MAC with Safari Browser Version 9.1.3 (9537.86.7.8).

2) Ran the script with the following command line based on what I read in the help menu and from the YouTube video entitled Tutorial 24: AndroidViewClient and Culebra and CulebraTester Demo. The YouTube demo show a Javascript executed with the following command line, but Javascript is not accessible on my CulebraTester browser menu.

curl -o - -v -X POST --data-urlenco @/Users/mtirone/Androidtest/Culebratester/calc1.py.txt http://10.100.20.123:9999/evaluatePythonscript

3) The Code Generation menu allows Python or Java to be selected, but the following are not selectable:
Javascript
Qunit
Java(Expresso)
Groovy

4) Result of running the command line in step 2.
- About to connect() to 10.100.20.123 port 9999 (#0)
-   Trying 10.100.20.123...
- Adding handle: conn: 0x7fc71900d600
- Adding handle: send: 0
- Adding handle: recv: 0
- Curl_addHandleToPipeline: length: 1
- \- Conn 0 (0x7fc71900d600) send_pipe: 1, recv_pipe: 0
- Connected to 10.100.20.123 (10.100.20.123) port 9999 (#0)
  > POST /evaluatePythonscript HTTP/1.1
  > User-Agent: curl/7.30.0
  > Host: 10.100.20.123:9999
  > Accept: _/_
  > Content-Length: 4886
  > Content-Type: application/x-www-form-urlencoded
  > Expect: 100-continue
  > 
  < HTTP/1.1 500 Internal Server Error 
  < Content-Type: application/json
  < Date: Wed, 19 Oct 2016 13:12:09 GMT
  < Connection: keep-alive
  < Content-Length: 71
- HTTP error before end of send, stop sending
  < 
- Closing connection 0
  { "status": "ERROR", "msg": "This feature requires an InApp Purchase" }

**Comment by dtmilano** [comment]
As indicated by the UI, and also as you mentioned, some languages have been disabled for code generation in this instalment. Python and Java (UiAutomator) are the top selected languages in the [opt-in form](http://goo.gl/forms/aqLL7ni6NH) so that's the main reason why they have been chosen first.

This allows us to focus on the issues that could be found generating those languages to reach the expected maturity soon.

Then to your specific question

> 1) Created a Python27 script on a MAC with Safari Browser Version 9.1.3 (9537.86.7.8).

That's perfect. Once you test script is generated you can run it as you do with any other [AndroidViewClient/culebra](https://github.com/dtmilano/AndroidViewClient) script.

This is a summary of the steps
1. Set **Python** as CulebraTester **Code Generation** language
2. Press SOURCE CODE **START** recording
3. Interact with the device representation
4. Once done. press SOURCE CODE **STOP**
5. Save the script using SOURCE CODE **SAVE** (you may have to remove the `.txt` extension)
6. Set the execution permission on the saved script using `chmod +x test.py`
7. Ensure that **AndroidViewClient** is in `PYTHONPATH` or set `ANDROID_VIEW_CLIENT_HOME` accordingly
8. Run `test.py`

The generated script contains the needed options to use CulebraTester as the backend (`'useuiautomatorhelper': True`) so the script will connect to automatically to your device.

Hope this helps.
Don't hesitate to ask more questions or create some issues if you find them.

**Comment by 7ikPDYl3** [comment]
Hi Diego,

Thanks! That worked. I'm getting the following error when I execute the test.py file. I'm just creating a basic test by clicking on the Calculator application and selecting number buttons. I'll document the issue after I'm sure it is not a configuration issue.

self.vc.click(oid=2)

TypeError: click() got an unexpected keyword argument 'oid'

Also, is the test.java file complied with javac to produce a test.jar file to run a test?

Regards,

Mike Tirone

**Comment by dtmilano** [comment]
If you haven't done it yet update to **CulebraTester 0.8.16** and [AndroidViewClient/culebra v 12.1.2](https://github.com/dtmilano/AndroidViewClient/releases/tag/v12.1.2).

A lot of fixes are there.

Just tried what you said:
- home
- all apps
- calculator
- 2 + 1

and this is the script generated which works as expected

``` python
#! /usr/bin/env python
# -*- coding: utf-8 -*-
'''
Copyright (C) 2013-2016  Diego Torres Milano
Created on 2016-10-25 by CulebraTester 
                      __    __    __    __
                     /  \  /  \  /  \  /  \ 
____________________/  __\/  __\/  __\/  __\_____________________________
___________________/  /__/  /__/  /__/  /________________________________
                   | / \   / \   / \   / \   \___
                   |/   \_/   \_/   \_/   \    o \ 
                                           \_____/--<
@author: Diego Torres Milano
@author: Jennifer E. Swofford (ascii art snake)
'''


import re
import sys
import os


import unittest
try:
    sys.path.insert(0, os.path.join(os.environ['ANDROID_VIEW_CLIENT_HOME'], 'src'))
except:
    pass

from com.dtmilano.android.viewclient import ViewClient, CulebraTestCase
from com.dtmilano.android.uiautomator.uiautomatorhelper import UiAutomatorHelper, UiScrollable, UiObject, UiObject2

TAG = 'CULEBRA'


class CulebraTests(CulebraTestCase):

    @classmethod
    def setUpClass(cls):
        cls.kwargs1 = {'ignoreversioncheck': False, 'verbose': False, 'ignoresecuredevice': False}
        cls.kwargs2 = {'forceviewserveruse': False, 'useuiautomatorhelper': True, 'ignoreuiautomatorkilled': True, 'autodump': False, 'startviewserver': True, 'compresseddump': True}
        cls.options = {'start-activity': None, 'concertina': False, 'device-art': None, 'use-jar': False, 'multi-device': False, 'unit-test-class': True, 'save-screenshot': None, 'use-dictionary': False, 'glare': False, 'dictionary-keys-from': 'id', 'scale': 1, 'find-views-with-content-description': True, 'window': -1, 'orientation-locked': None, 'save-view-screenshots': None, 'find-views-by-id': True, 'log-actions': False, 'use-regexps': False, 'null-back-end': False, 'auto-regexps': None, 'do-not-verify-screen-dump': True, 'verbose-comments': False, 'gui': False, 'find-views-with-text': True, 'prepend-to-sys-path': False, 'install-apk': None, 'drop-shadow': False, 'output': None, 'unit-test-method': None, 'interactive': False}
        cls.sleep = 5

    def setUp(self):
        super(CulebraTests, self).setUp()

    def tearDown(self):
        super(CulebraTests, self).tearDown()

    def preconditions(self):
        if not super(CulebraTests, self).preconditions():
            return False
        return True

    def testSomething(self):
        if not self.preconditions():
            self.fail('Preconditions failed')

        _s = CulebraTests.sleep
        _v = CulebraTests.verbose

        self.vc.uiAutomatorHelper.pressHome()
        self.vc.sleep(_s)
        self.vc.uiAutomatorHelper.findObject(bySelector='desc@Apps,package@com.android.launcher3').clickAndWait(eventCondition='until:newWindow', timeout=_s*1000)
        UiScrollable(self.vc.uiAutomatorHelper, uiSelector='res@com.android.launcher3:id/apps_list_view,package@com.android.launcher3').getChildByDescription(uiSelector='desc@Calculator', description="Calculator", allowScrollSearch=True).click()
        UiScrollable(self.vc.uiAutomatorHelper, uiSelector='res@com.android.calculator2:id/pad_pager,index@1,package@com.android.calculator2').getChildByText(uiSelector='text@2', text="2", allowScrollSearch=True).click()
        UiScrollable(self.vc.uiAutomatorHelper, uiSelector='res@com.android.calculator2:id/pad_pager,index@1,package@com.android.calculator2').getChildByDescription(uiSelector='desc@plus', description="plus", allowScrollSearch=True).click()
        UiScrollable(self.vc.uiAutomatorHelper, uiSelector='res@com.android.calculator2:id/pad_pager,index@1,package@com.android.calculator2').getChildByText(uiSelector='text@1', text="1", allowScrollSearch=True).click()

if __name__ == '__main__':
    CulebraTests.main()
```

**Comment by 7ikPDYl3** [comment]
Hi Diego,
The following link is a video of how I’m generating the Python27 script. I updated using easyinstall and the version shows 12.2.0.

https://dl.dropboxusercontent.com/u/59429708/Diego/culebratesterpython27.mov

The following is the error message I get when I run the .py script.
Regards,
Mike Tirone

# E

## ERROR: testSomething (**main**.CulebraTests)

Traceback (most recent call last):
  File "./test1.py", line 61, in testSomething
    self.vc.click(oid=2)
TypeError: click() got an unexpected keyword argument 'oid'

---

Ran 1 test in 5.904s

FAILED (errors=1)

## Culebra Tester: Debug Info Helper

Platform

Device

falcon_umts

Brand

motorola

Board

MSM8226

Hardware

motorola

Model

XT1034

API

19

Build

qcom KXB20.9-1.10-1.24-1.1 TA88000JUO

Build number

KXB20.9-1.10-1.24-1.1

APK

version code

8014

version name

0.8.14

Display

Size

720x1280

**Comment by dtmilano** [comment]
The video is really helpful.
All the problems you are seeing should be fixed in **0.8.17**.
Let me know.

**Comment by dtmilano** [comment]
I uploaded a video doing (almost) exactly the same: https://youtu.be/TeJNBU_5TAg

**Comment by dtmilano** [comment]
Latest **CulebraTester** versions specify the minimum required AndroidViewClient version to run the generated script.
