### ISSUE TITLE
culebra "Instrumentation is not running" keeps showing after execute curl commad then press DONE.

### ISSUE THREAD

**Issue by yamatakau08** [dtmilano/CulebraTester-public#9]
Dear Diego,

I type the URL  "Culebra Tester" app showed at PC web browser.
we browser "culebra" tab instruct me to put "curl ... " command.
I type command on Cygwin terminal the following.

[terminal on Cygwin]
```
yama@roswell:~$ curl -s http://192.168.0.132:9999/Assets/runinstrumentation.sh | bash
1) CB5A224CBF   device
2)
Select the device to use, <Q> to quit: 1

com.dtmilano.android.uiautomatorhelper.UiAutomatorHelper:
```

It looks to work.
Then I press "DONE" in the dialog.
But dialog doesn't close.
"Culebra Tester" app keeps showing at Android device.

What is wrong with my operation?

**Comment by dtmilano** [comment]
Once you see the output of the instrumentation running

    com.dtmilano.android.uiautomatorhelper.UiAutomatorHelper:

you should leave it open and it will run until you send the QUIT command from the browser.
